/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Config {
  created_at: Generated<number | null>;
  key: string;
  updated_at: Generated<number | null>;
  value: string;
}

export interface Flows {
  created_at: Generated<number | null>;
  id: string;
  parent_id: string | null;
  status: Generated<string>;
  taints: Generated<string>;
  title: string | null;
  updated_at: Generated<number | null>;
}

export interface Messages {
  content: string;
  created_at: Generated<number | null>;
  flow_id: string;
  id: string;
  role: string;
  taints: Generated<string>;
}

export interface Secrets {
  created_at: Generated<number | null>;
  key: string;
  updated_at: Generated<number | null>;
  value: string;
}

export interface DB {
  config: Config;
  flows: Flows;
  messages: Messages;
  secrets: Secrets;
}
