name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init --recursive
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          registry-url: https://registry.npmjs.org

      - run: cd packages/capnweb && npm ci && npm run build
      - run: npm ci
      - run: npm run build
      - run: ./bin/bump-and-publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
